In [1]:
from Utilities.trading_tools.VaR_calculator import VaR_calculator

import pandas as pd
import numpy as np
import datetime as dt

In [2]:
inst = VaR_calculator()

In [7]:
positions = [[['DE_B_M_5_25', 'DE_P_M_5_25'], [1,-1], [-1]],
            [['DE_B_M_4_25', 'FR_B_M_4_25'], [1,-1], [0]],
            [['DE_B_Q_2_25', 'FR_B_Q_2_25'], [1,-1], [1]],
            [['DE_B_Q_4_25', 'FR_B_Q_4_25'], [1,-1], [0.5]],
            [['DE_B_M_5_25', 'FR_B_M_5_25'], [1,-1], [1]],
            [['DE_B_M_6_25', 'FR_B_M_6_25'], [1,-1], [-1]],
            [['IT_B_Y_1_25', 'HU_B_Y_1_25'], [1,-1], [1]],
            [['IT_B_M_5_25', 'IT_B_M_6_25'], [1,-1], [3]],
            [['DE_B_M_7_25', 'DE_P_M_8_25'], [1,-1], [4]]]
            # [['FR_B_Y_1_26', 'FR_B_Y_1_27'], [1,-1],[1]]]

In [8]:
var_results = inst.calculate_var(positions=positions,
                            # portfolio_size=4,
                            percentile=0.9)

In [9]:
var_results['individual_var']

,Asset,Weight,Hours,Daily VaR,Weekly VaR,Monthly VaR,Quarterly VaR,Yearly VaR
0,DE_B_M_5_25xDE_P_M_5_25,-1.0,744,542.073380,1212.112927,2484.092297,4302.574069,8605.148137
1,DE_B_M_4_25xFR_B_M_4_25,0.0,720,0.000000,0.000000,0.000000,0.000000,0.000000
2,DE_B_Q_2_25xFR_B_Q_2_25,1.0,2184,2465.055650,5512.032002,11296.304109,19565.772654,39131.545308
3,DE_B_Q_4_25xFR_B_Q_4_25,0.5,2208,946.602986,2116.668624,4337.879835,7513.428271,15026.856542
4,DE_B_M_5_25xFR_B_M_5_25,1.0,744,1025.130505,2292.261494,4697.738135,8136.721130,16273.442261
5,DE_B_M_6_25xFR_B_M_6_25,-1.0,720,935.303992,2091.403306,4286.101342,7423.745290,14847.490580
6,IT_B_Y_1_25xHU_B_Y_1_25,1.0,8760,14959.557402,33450.587265,68553.304159,118737.805831,237475.611662
7,IT_B_M_5_25xIT_B_M_6_25,3.0,744,3262.610390,7295.418617,14951.159077,25896.167154,51792.334307
8,DE_B_M_7_25xDE_P_M_8_25,4.0,744,3247.650575,7261.967452,14882.604589,25777.427297,51554.854594

In [10]:
var_results['portfolio_var']

,Combination,Weights,Daily VaR,Weekly VaR,Monthly VaR,Quarterly VaR,Yearly VaR
0,"(DE_B_M_5_25xDE_P_M_5_25, DE_B_M_4_25xFR_B_M_4...","[-744, 0, 2184, 1104.0, 744, -720, 8760, 2232,...",15465.621643,34582.181309,70872.38185,122754.566217,245509.132434

In [7]:
positions = [[['DE_B_M_4_25', 'DE_B_M_5_25'], [1,-1], [-1]],
            [['DE_B_M_4_25'], [1,], [1]],
            [['DE_B_M_5_25'], [1], [1]],
            [['DE_B_Q_2_25'], [1], [1]],
            [['DE_B_Y_1_26'], [1], [1]]]

In [25]:
var_results2 = inst.calculate_var(positions=positions,
                            portfolio_size=len(positions)-1,
                            percentile=0.9)

In [26]:
var_results2['individual_var']

,Asset,Weight,Hours,Daily VaR,Weekly VaR,Monthly VaR,Quarterly VaR,Yearly VaR
0,DE_B_M_5_25xDE_P_M_5_25,-1,744,555.279459,1241.642617,2544.610153,4407.394070,8814.788139
1,DE_B_M_4_25xFR_B_M_4_25,-1,720,1018.719951,2277.927060,4668.361287,8085.838937,16171.677874
2,DE_B_Q_2_25xFR_B_Q_2_25,1,2184,2432.702463,5439.688076,11148.043179,19308.977191,38617.954382
3,DE_B_M_5_25xFR_B_M_5_25,1,744,1025.376348,2292.811217,4698.864731,8138.672451,16277.344902
4,DE_B_M_6_25xFR_B_M_6_25,-1,720,948.113893,2120.047116,4344.803683,7525.420729,15050.841457
5,IT_B_Y_1_25xHU_B_Y_1_25,1,8760,15364.322362,34355.669229,70408.170224,121950.528095,243901.056191
6,IT_B_M_5_25xIT_B_M_6_25,3,744,3357.102819,7506.710110,15384.177783,26646.177553,53292.355105
7,DE_B_M_7_25xDE_P_M_8_25,4,744,3314.999989,7412.565321,15191.238378,26311.996701,52623.993402
8,FR_B_Y_1_26xFR_B_Y_1_27,1,8760,6075.216348,13584.596732,27840.138778,48220.534853,96441.069705

In [34]:
var_results2['portfolio_var'].iloc[3]

Combination      (DE_B_M_5_25xDE_P_M_5_25, DE_B_M_4_25xFR_B_M_4...
Weights            [-744, -720, 2184, 744, -720, 2232, 2976, 8760]
Daily VaR                                              7376.389344
Weekly VaR                                            16494.108002
Monthly VaR                                           33802.862524
Quarterly VaR                                         58548.275333
Yearly VaR                                           117096.550667
Name: 3, dtype: object