In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from datetime import datetime, time, timedelta
from SynthSpread.spreadviewer_class import SpreadSingle, SpreadViewerData, norm_coeff
from Database.TPData import TPData, TPDataDa, TPDataAssembly
from Strategies.MultipleMarketsIntensity_class import MultiTradeIntensity as TI
from Math.ti_class import TI_class, VI_class, TR_class
from Math.lm_class import kalman, LinearModel
from Math.accumfeatures import EMA, MA, MSTD, DifferentialEMA, DerivativeEMA
from Strategies.IntensityHawkes_strategy.model_class import HawkesIntensity
from Strategies.IntensityHawkes_strategy.backtest_class import BacktestIB
from Strategies.IntensityHawkes_strategy.strategy_class import StrategyHI, VolumeClass
tol=(1e-1)/2

# Data Loading

In [3]:
params_dict = {}

params_dict['tenor_list'] = ['m']
params_dict['tn1_list'] = [1]
params_dict['mkt_list'] = ['de'] * len(params_dict['tenor_list'])
params_dict['tn2_list'] = []
params_dict['prod'] = 'base'
params_dict['venue_list'] = ['eex']*len(params_dict['mkt_list'])
params_dict['start_date'] = datetime(2024, 6, 20)
params_dict['end_date'] = datetime(2024, 6, 20)
params_dict['ns'] = 2

# Fetch trades and best orders for the curve
assembler = TPDataAssembly(source='trayport', user='matej')
# assembler.set_start_end_time(start=[10,0,0], end=[12,0,0])    
trades_dict = assembler.get_data(params_dict, target_data='trades')
#assembler.set_data_source('database')
ba_dict = assembler.get_data(params_dict, target_data='best_orders')

assert ba_dict.keys() == trades_dict.keys(), "Curve doesn't fit for both trades and best_orders"

trades = pd.DataFrame()
ba = pd.DataFrame()
products = []
for key in trades_dict.keys():
    ba_aux = ba_dict[key].copy()
    trade_aux = trades_dict[key].copy()
    trade_aux.columns = [a + '_' + key for a in trade_aux.columns]
    ba_aux.columns = [a + '_' + key for a in ba_aux.columns]
    if trades.empty:
        trades = trade_aux.copy()
    else:
        trades = pd.concat([trades, trade_aux])
    if ba.empty:
        ba = ba_aux.copy()
    else:
        ba = pd.concat([ba, ba_aux])
    products.append(key)
trades.sort_index(inplace=True)
ba.sort_index(inplace=True)
ba.index.name='datetime'

ti_inst = TI(trades, ba, products)

ti_inst.prepare_data()


data_raw = ti_inst.data

# data = data_raw[data_raw['broker_id_dew1']==1441][['price_dew1', 'volume_dew1','bidbestprice_dew1',
#                   'askbestprice_dew1', 'mid_dew1', 'trade_side_dew1']].copy()

data = data_raw[['price_dem1', 'volume_dem1','bidbestprice_dem1',
                   'askbestprice_dem1', 'mid_dem1', 'trade_side_dem1']].copy()
    
data.columns = [a.split('_')[0] for a in data.columns]
data.columns = ['trd_price', 'volume', 'bid_price', 'ask_price', 'mid_price', 'trd_side']

data.to_csv(r's:\Algo\Files\andrej\Data\int_data_lead_production_sample.csv')

https://referencedata.trayport.com/instruments
Duration: 2.142s

KeyboardInterrupt:

# Parsing calibration results simple

In [7]:
# Load the pickled object
import pickle
with open(r'out_dict_deq1_dem1_07032024.pkl', 'rb') as file:
    loaded_object = pickle.load(file)

df=pd.DataFrame([(k[0],k[1],k[2], k[3], k[4], v) for k,v in loaded_object.items()], columns=['param_max_secs_between_trades',
                                                                                          'param_cluster_trade_num_threshold',
                                                                                          'param_min_price_movement',
                                                                                          'param_take_profit',
                                                                                          'param_stop_loss',
                                                                                          
                                                                                           'cumpnl']).sort_values(by=['cumpnl'], ascending=False)

In [8]:
filter1=df['param_min_price_movement']>0.1
filter2=df['param_take_profit']>=df['param_stop_loss'].apply(abs)
filter3=df['param_max_secs_between_trades']<45

filter=filter1&filter2&filter3


df[filter][0:50]

,param_max_secs_between_trades,param_cluster_trade_num_threshold,param_min_price_movement,param_take_profit,param_stop_loss,cumpnl
335,4,0.009,2.25,10,False,2.245
334,4,0.009,2.25,10,True,2.245
333,4,0.009,2.00,10,False,-0.345
332,4,0.009,2.00,10,True,-0.345
76,1,0.009,1.50,10,True,-0.490
77,1,0.009,1.50,10,False,-0.490
330,4,0.009,1.75,10,True,-0.895
331,4,0.009,1.75,10,False,-0.895
328,4,0.009,1.50,10,True,-1.135
329,4,0.009,1.50,10,False,-1.135
288,4,0.006,1.00,10,True,-1.220
289,4,0.006,1.00,10,False,-1.220
299,4,0.006,2.25,10,False,-1.690
298,4,0.006,2.25,10,True,-1.690
260,4,0.003,2.00,10,True,-1.790
261,4,0.003,2.00,10,False,-1.790
269,4,0.004,1.50,10,False,-1.985
268,4,0.004,1.50,10,True,-1.985
107,2,0.004,2.25,10,False,-2.080
106,2,0.004,2.25,10,True,-2.080
259,4,0.003,1.75,10,False,-2.565
258,4,0.003,1.75,10,True,-2.565
272,4,0.004,2.00,10,True,-2.870
273,4,0.004,2.00,10,False,-2.870
255,4,0.003,1.25,10,False,-2.940
254,4,0.003,1.25,10,True,-2.940
262,4,0.003,2.25,10,True,-3.065
263,4,0.003,2.25,10,False,-3.065
266,4,0.004,1.25,10,True,-3.110
267,4,0.004,1.25,10,False,-3.110
276,4,0.005,1.00,10,True,-3.300
277,4,0.005,1.00,10,False,-3.300
264,4,0.004,1.00,10,True,-3.335
265,4,0.004,1.00,10,False,-3.335
34,1,0.005,2.25,10,True,-3.540
35,1,0.005,2.25,10,False,-3.540
278,4,0.005,1.25,10,True,-3.555
279,4,0.005,1.25,10,False,-3.555
318,4,0.008,1.75,10,True,-3.790
319,4,0.008,1.75,10,False,-3.790
271,4,0.004,1.75,10,False,-3.960
270,4,0.004,1.75,10,True,-3.960
291,4,0.006,1.25,10,False,-4.005
290,4,0.006,1.25,10,True,-4.005
257,4,0.003,1.50,10,False,-4.105
256,4,0.003,1.50,10,True,-4.105
326,4,0.009,1.25,10,True,-4.435
327,4,0.009,1.25,10,False,-4.435
322,4,0.008,2.25,10,True,-4.595
323,4,0.008,2.25,10,False,-4.595

# Parsing calibration results new

## dew1_dem1

### Fixed Take profit

In [40]:
# Load the pickled object
import pickle
with open(r's:\Algo\Files\andrej\LeadLag\out_dict_dew1_dem1_20240621.pkl', 'rb') as file:
    loaded_object = pickle.load(file)

df=pd.DataFrame([(k[0],k[1],k[2], k[3], k[4], v[0],v[1],v[2], v[3], v[4]) for k,v in loaded_object.items()], columns=['MSBT',
                                                                                          'CTNM',
                                                                                          'MPM',
                                                                                          'TP',
                                                                                          'SL',
                                                                                          
                                                                                           'cumpnl', 'sharp', 'max_drawdown', 'num_trades', 'trade_per_day']).sort_values(by=['sharp'], ascending=False)

In [41]:
filter1=df['MPM']>0.1
filter2=True#df['TP']>=df['SL'].apply(abs)
filter3=df['num_trades']>40

filter=filter1&filter2&filter3


df[filter][0:50]

,MSBT,CTNM,MPM,TP,SL,cumpnl,sharp,max_drawdown,num_trades,trade_per_day
3344,10,9,0.2,1.00,-0.40,5.095,2.786019,3.1950,62,1.441860
3345,10,9,0.2,1.00,-0.50,4.045,2.748145,4.0550,60,1.395349
3346,10,9,0.2,1.00,-0.75,3.020,2.660105,3.7550,54,1.255814
3347,10,9,0.2,1.00,-1.00,1.275,2.461024,4.4900,52,1.209302
6981,30,17,0.3,1.00,-0.50,2.735,2.412272,2.7750,50,1.162791
3340,10,9,0.2,0.75,-0.75,3.170,2.339937,3.5000,56,1.302326
6947,30,17,0.2,1.00,-1.00,8.660,2.325259,6.2950,124,2.883721
3338,10,9,0.2,0.75,-0.40,4.945,2.324270,3.2300,64,1.488372
3339,10,9,0.2,0.75,-0.50,3.670,2.282473,3.8950,62,1.441860
3343,10,9,0.2,1.00,-0.30,1.670,2.244264,3.9400,62,1.441860
3332,10,9,0.2,0.50,-0.40,2.875,2.183301,3.4750,66,1.534884
3341,10,9,0.2,0.75,-1.00,0.705,2.139796,4.1950,54,1.255814
6946,30,17,0.2,1.00,-0.75,6.370,2.089189,6.8000,126,2.930233
6767,30,15,0.2,1.00,-1.00,2.900,1.964125,7.2950,122,2.837209
6587,30,13,0.2,1.00,-1.00,8.635,1.954514,4.8550,128,2.976744
3333,10,9,0.2,0.50,-0.50,1.600,1.927791,4.1400,64,1.488372
3326,10,9,0.2,0.40,-0.40,3.545,1.912688,2.3975,68,1.581395
6941,30,17,0.2,0.75,-1.00,7.390,1.896507,6.5400,132,3.069767
3334,10,9,0.2,0.50,-0.75,1.075,1.878532,3.6800,58,1.348837
3337,10,9,0.2,0.75,-0.30,1.825,1.850454,3.9400,64,1.488372
7127,30,19,0.2,1.00,-1.00,11.420,1.826646,7.2050,112,2.604651
6586,30,13,0.2,1.00,-0.75,10.620,1.821911,3.6700,132,3.069767
6940,30,17,0.2,0.75,-0.75,6.615,1.816814,6.4850,134,3.116279
6261,30,9,0.3,1.00,-0.50,0.520,1.813206,2.6850,54,1.255814
6766,30,15,0.2,1.00,-0.75,5.345,1.809065,5.8750,122,2.837209
6581,30,13,0.2,0.75,-1.00,8.055,1.780098,5.5500,140,3.255814
3327,10,9,0.2,0.40,-0.50,2.270,1.761402,3.0625,66,1.534884
7121,30,19,0.2,0.75,-1.00,7.535,1.695026,7.4500,118,2.744186
3320,10,9,0.2,0.30,-0.40,3.850,1.691287,2.1775,70,1.627907
7126,30,19,0.2,1.00,-0.75,8.765,1.689963,7.6650,114,2.651163
6580,30,13,0.2,0.75,-0.75,11.090,1.664129,4.1300,144,3.348837
6945,30,17,0.2,1.00,-0.50,11.825,1.648739,4.9400,138,3.209302
3164,10,7,0.2,1.00,-0.40,1.000,1.629509,2.7750,72,1.674419
3152,10,7,0.2,0.50,-0.40,0.795,1.612583,3.1325,76,1.767442
6975,30,17,0.3,0.75,-0.50,2.685,1.607202,3.3150,54,1.255814
6923,30,17,0.2,0.30,-1.00,1.540,1.602895,4.0225,148,3.441860
7161,30,19,0.3,1.00,-0.50,1.870,1.601970,2.9650,48,1.116279
3328,10,9,0.2,0.40,-0.75,1.760,1.581069,3.3950,60,1.395349
7103,30,19,0.2,0.30,-1.00,2.220,1.574254,5.1075,132,3.069767
6585,30,13,0.2,1.00,-0.50,12.680,1.569344,3.6250,140,3.255814
4785,20,9,0.2,1.00,-0.50,2.095,1.565627,6.3900,116,2.697674
7120,30,19,0.2,0.75,-0.75,7.520,1.556823,7.9800,120,2.790698
3524,10,11,0.2,1.00,-0.40,3.600,1.546926,2.5425,56,1.302326
6761,30,15,0.2,0.75,-1.00,2.715,1.543756,7.5400,130,3.023256
6760,30,15,0.2,0.75,-0.75,6.730,1.513285,6.1200,132,3.069767
6801,30,15,0.3,1.00,-0.50,0.750,1.506851,2.2200,48,1.116279
6922,30,17,0.2,0.30,-0.75,2.075,1.503498,4.8125,148,3.441860
6621,30,13,0.3,1.00,-0.50,2.245,1.479077,2.6050,44,1.023256
3321,10,9,0.2,0.30,-0.50,2.715,1.478809,2.2925,68,1.581395
3146,10,7,0.2,0.40,-0.40,-0.005,1.477839,3.2825,76,1.767442

### With action closing

In [43]:
# Load the pickled object
import pickle
with open(r's:\Algo\Files\andrej\LeadLag\out_dict_dew1_dem1_20240624.pkl', 'rb') as file:
    loaded_object = pickle.load(file)

df=pd.DataFrame([(k[0],k[1],k[2], k[3], k[4], v[0],v[1],v[2], v[3], v[4]) for k,v in loaded_object.items()], columns=['MSBT',
                                                                                          'CTNM',
                                                                                          'MPM',
                                                                                          'TP',
                                                                                          'SL',
                                                                                          
                                                                                           'cumpnl', 'sharp', 'max_drawdown', 'num_trades', 'trade_per_day']).sort_values(by=['cumpnl'], ascending=False)

In [44]:
filter1=df['MPM']>=0.1
filter2=df['SL']<-0.1
filter3=df['MSBT']<100

filter=filter1&filter2&filter3


df[filter][0:50]

,MSBT,CTNM,MPM,TP,SL,cumpnl,sharp,max_drawdown,num_trades,trade_per_day
0,10,9,0.2,1.0,-0.4,3.765,2.707579,3.76,62,1.44186

## deq1_dem1

### Fixed Take profit

In [20]:
# Load the pickled object
import pickle
with open(r'out_dict_deq1_dem1_08032024.pkl', 'rb') as file:
    loaded_object = pickle.load(file)

df=pd.DataFrame([(k[0],k[1],k[2], k[3], k[4], v[0],v[1],v[2], v[3], v[4]) for k,v in loaded_object.items()], columns=['MSBT',
                                                                                          'CTNM',
                                                                                          'MPM',
                                                                                          'TP',
                                                                                          'SL',
                                                                                          
                                                                                           'cumpnl', 'sharp', 'max_drawdown', 'num_trades', 'trade_per_day']).sort_values(by=['cumpnl'], ascending=False)

In [21]:
filter1=df['MPM']>0.0
filter2=df['TP']>=df['SL'].apply(abs)
filter3=df['MSBT']<100

filter=filter1&filter2&filter3


df[filter][0:50]

,MSBT,CTNM,MPM,TP,SL,cumpnl,sharp,max_drawdown,num_trades,trade_per_day
4546,30,3,0.10,2.00,-0.75,27.060,0.436153,11.2475,198,4.829268
7045,50,7,0.10,2.00,-0.50,25.480,2.368636,9.1950,230,5.609756
5636,40,3,0.05,1.00,-0.75,24.985,1.176155,6.4275,304,7.414634
7948,60,3,0.20,2.00,-1.50,24.465,0.987591,5.9800,130,3.170732
7895,60,3,0.05,2.00,-0.50,24.060,2.138794,9.5650,308,7.512195
5637,40,3,0.05,1.00,-1.00,24.055,1.534391,6.9550,274,6.682927
4549,30,3,0.10,2.00,-2.00,23.740,0.888648,9.3200,132,3.219512
6772,50,3,0.05,2.00,-1.00,23.580,1.221613,7.5550,218,5.317073
6823,50,3,0.20,2.00,-1.50,23.390,1.104941,4.6800,122,2.975610
8286,60,9,0.10,1.00,-0.75,23.375,1.919319,4.6600,258,6.292683
7949,60,3,0.20,2.00,-2.00,21.875,0.766191,7.4850,112,2.731707
6824,50,3,0.20,2.00,-2.00,21.780,0.918984,5.2650,108,2.634146
2548,10,7,0.10,2.00,-1.50,21.105,1.681800,4.7000,84,2.048780
5399,30,17,0.05,2.00,-2.00,20.945,1.324374,9.2425,86,2.097561
4548,30,3,0.10,2.00,-1.50,20.800,-0.129528,16.6200,152,3.707317
5398,30,17,0.05,2.00,-1.50,20.775,1.272133,8.8275,88,2.146341
4537,30,3,0.10,1.00,-1.00,20.755,0.881326,8.8225,230,5.609756
7947,60,3,0.20,2.00,-1.00,20.370,0.583149,7.8350,140,3.414634
6774,50,3,0.05,2.00,-2.00,19.780,0.843386,9.7850,154,3.756098
6771,50,3,0.05,2.00,-0.75,19.410,1.711617,10.4600,256,6.243902
7897,60,3,0.05,2.00,-1.00,19.255,1.077808,11.4300,214,5.219512
6799,50,3,0.10,2.00,-2.00,18.765,0.939993,7.6150,150,3.658537
7892,60,3,0.05,1.50,-1.00,18.475,1.289575,11.1200,240,5.853659
6795,50,3,0.10,2.00,-0.50,18.410,1.437570,8.3100,284,6.926829
4547,30,3,0.10,2.00,-1.00,18.265,-0.160159,13.7275,186,4.536585
4273,20,17,0.05,2.00,-1.50,18.175,1.685306,2.6050,48,1.170732
4274,20,17,0.05,2.00,-2.00,17.970,1.682022,2.4900,48,1.170732
7040,50,7,0.10,1.50,-0.50,17.755,2.259763,9.1200,248,6.048780
6773,50,3,0.05,2.00,-1.50,17.735,0.191531,10.1275,182,4.439024
6031,40,9,0.10,0.75,-0.75,17.565,1.270297,4.6200,272,6.634146
8696,60,15,0.20,2.00,-0.75,17.400,1.336505,7.3800,138,3.365854
8437,60,11,0.20,1.00,-1.00,17.340,1.514827,4.6750,178,4.341463
4536,30,3,0.10,1.00,-0.75,17.250,0.645627,7.5275,250,6.097561
4521,30,3,0.05,2.00,-0.75,16.975,0.751263,8.1400,210,5.121951
6036,40,9,0.10,1.00,-0.75,16.895,1.449481,5.2000,224,5.463415
8423,60,11,0.10,2.00,-1.50,16.805,1.009362,9.4950,136,3.317073
5423,30,17,0.10,2.00,-1.50,16.780,1.212570,8.9200,76,1.853659
4268,20,17,0.05,1.50,-1.50,16.770,1.637322,2.0550,48,1.170732
6012,40,9,0.05,1.00,-1.00,16.725,1.025765,6.2650,220,5.365854
4299,20,17,0.10,2.00,-2.00,16.660,1.724281,3.0700,46,1.121951
4272,20,17,0.05,2.00,-1.00,16.390,1.816837,2.0750,48,1.170732
4298,20,17,0.10,2.00,-1.50,16.375,1.732578,3.2350,46,1.121951
8261,60,9,0.05,1.00,-0.75,16.335,1.648159,9.7500,286,6.975610
2523,10,7,0.05,2.00,-1.50,16.330,1.444810,6.5900,106,2.585366
5662,40,3,0.10,1.00,-1.00,16.310,0.968730,7.0700,258,6.292683
4574,30,3,0.20,2.00,-2.00,16.310,0.420706,11.8700,106,2.585366
8442,60,11,0.20,1.50,-1.00,16.295,1.419052,5.2925,164,4.000000
8296,60,9,0.10,2.00,-0.75,16.145,1.742223,6.7350,210,5.121951
4545,30,3,0.10,2.00,-0.50,16.070,0.554687,7.8050,246,6.000000
6011,40,9,0.05,1.00,-0.75,16.060,1.062863,5.6500,236,5.756098

### Trailing Take profit

In [22]:
# Load the pickled object
import pickle
with open(r'out_dict_deq1_dem1_trailing_tp_13032024.pkl', 'rb') as file:
    loaded_object = pickle.load(file)

df=pd.DataFrame([(k[0],k[1],k[2], k[3], k[4], v[0],v[1],v[2], v[3], v[4]) for k,v in loaded_object.items()], columns=['MSBT',
                                                                                          'CTNM',
                                                                                          'MPM',
                                                                                          'TP',
                                                                                          'SL',
                                                                                          
                                                                                           'cumpnl', 'sharp', 'max_drawdown', 'num_trades', 'trade_per_day']).sort_values(by=['cumpnl'], ascending=False)

In [23]:
filter1=df['MPM']>0.0
filter2=df['TP']>=df['SL'].apply(abs)
filter3=df['MSBT']<100

filter=filter1&filter2&filter3


df[filter][0:50]

,MSBT,CTNM,MPM,TP,SL,cumpnl,sharp,max_drawdown,num_trades,trade_per_day
5637,50,7,0.10,1.0,-0.50,23.515,2.064483,9.1200,252,6.146341
6317,60,3,0.05,1.0,-0.50,21.545,2.392419,9.8300,350,8.536585
5718,50,9,0.05,1.0,-0.75,20.530,1.083311,7.9000,220,5.365854
5638,50,7,0.10,1.0,-0.75,19.405,2.869682,9.2250,228,5.560976
5179,40,15,0.30,1.0,-1.00,18.785,2.252047,2.9850,60,1.463415
6711,60,11,0.05,0.5,-0.30,18.510,1.734927,4.5450,384,9.365854
5612,50,7,0.05,0.5,-0.50,17.715,1.820608,13.0600,378,9.219512
4717,40,7,0.05,1.0,-0.50,15.910,1.912262,8.8650,270,6.585366
6731,60,11,0.10,0.5,-0.30,15.860,2.069982,4.4250,334,8.146341
5436,50,3,0.10,1.0,-0.30,15.435,1.207507,7.5000,394,9.609756
5617,50,7,0.05,1.0,-0.50,15.425,1.838838,10.7150,306,7.463415
6359,60,3,0.20,1.0,-1.00,15.265,0.244746,8.4600,158,3.853659
6518,60,7,0.05,1.0,-0.75,15.255,1.127054,13.7500,254,6.195122
6618,60,9,0.05,1.0,-0.75,15.130,1.236638,8.4150,248,6.048780
5178,40,15,0.30,1.0,-0.75,14.990,1.841838,3.3000,56,1.365854
6756,60,11,0.20,1.0,-0.30,14.725,1.524838,6.3850,232,5.658537
6336,60,3,0.10,1.0,-0.30,14.470,0.934266,6.2600,394,9.609756
6978,60,15,0.30,1.0,-0.75,14.435,0.397708,5.2500,118,2.878049
5719,50,9,0.05,1.0,-1.00,14.425,1.275818,11.1300,204,4.975610
5859,50,11,0.20,1.0,-1.00,14.410,0.548603,5.4550,134,3.268293
4939,40,11,0.10,1.0,-1.00,13.820,1.505924,8.1100,156,3.804878
5437,50,3,0.10,1.0,-0.50,13.815,1.032201,8.8200,308,7.512195
6759,60,11,0.20,1.0,-1.00,13.790,1.436460,4.6075,162,3.951220
6316,60,3,0.05,1.0,-0.30,13.685,1.423204,9.7350,466,11.365854
4819,40,9,0.05,1.0,-1.00,13.610,1.122286,7.4250,194,4.731707
6337,60,3,0.10,1.0,-0.50,13.580,0.496028,8.5200,306,7.463415
6332,60,3,0.10,0.5,-0.50,13.575,0.686418,5.9950,376,9.170732
6335,60,3,0.10,1.0,-0.20,13.505,0.845691,4.8850,492,12.000000
4818,40,9,0.05,1.0,-0.75,13.485,1.125826,8.4600,210,5.121951
5418,50,3,0.05,1.0,-0.75,13.395,1.135314,10.9050,288,7.024390
5435,50,3,0.10,1.0,-0.20,13.135,0.605730,6.0350,484,11.804878
3839,30,7,0.10,1.0,-1.00,12.890,2.871734,8.4050,156,3.804878
4732,40,7,0.10,0.5,-0.50,12.620,1.592927,5.9700,276,6.731707
6751,60,11,0.20,0.5,-0.30,12.370,1.822744,7.8450,264,6.439024
6896,60,13,0.40,1.0,-0.30,12.350,1.042747,2.4200,72,1.756098
5738,50,9,0.10,1.0,-0.75,12.165,1.294042,10.5550,210,5.121951
4938,40,11,0.10,1.0,-0.75,12.140,1.654901,5.8050,170,4.146341
6538,60,7,0.10,1.0,-0.75,11.875,1.358981,11.8300,250,6.097561
6758,60,11,0.20,1.0,-0.75,11.840,1.368779,5.1700,174,4.243902
3419,20,17,0.05,1.0,-1.00,11.805,2.008381,2.1100,50,1.219512
6736,60,11,0.10,1.0,-0.30,11.765,1.231983,3.9150,300,7.317073
6638,60,9,0.10,1.0,-0.75,11.735,1.054881,6.5000,232,5.658537
6312,60,3,0.05,0.5,-0.50,11.665,2.239591,8.0700,430,10.487805
6876,60,13,0.30,1.0,-0.30,11.480,0.597634,2.2400,100,2.439024
6712,60,11,0.05,0.5,-0.50,11.450,1.310812,5.6950,332,8.097561
5618,50,7,0.05,1.0,-0.75,11.420,2.450796,12.2400,266,6.487805
5419,50,3,0.05,1.0,-1.00,11.375,0.899334,10.5100,242,5.902439
6919,60,15,0.05,1.0,-1.00,11.360,-0.359243,10.7550,186,4.536585
6512,60,7,0.05,0.5,-0.50,11.340,1.589524,8.6750,398,9.707317
3918,30,9,0.05,1.0,-0.75,11.175,0.392613,7.8000,190,4.634146